# Base configs
baseurl: "https://kheeirul96.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Kheeirul Amidzal"
subtitle: "See the world through my eyes!"
author: "Kheeirul Amidzal"
header:
 title: "Photography"
 subtitle: "by Kheeirul Amidzal"
footer:
 name: "Hey there, my name is Kheeirul"
 bio: "I am a developer and undergraduate from Malaysia. Love making teeny tiny apps solving tiny problems in life and now learning photography."
 github: "Want a website like this for yourself for free? Just <a href=\"https://kheeirul96.github.io/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/"
  twitter: "https://www.twitter.com/"
  instagram: "https://www.instagram.com/"
  dribbble: "https://dribbble.com/"
  linkedin: "https://in.linkedin.com/in/kheeirul96"
  github: "https://www.github.com/kheeirul96"
